### ISSUE TITLE
Manage Products app is not working

### ISSUE THREAD

**Issue by ahmedkhan29789** [jcailan/cap-fe-samples#2]
Hi,

I have cloned your APP in my BAS, Ran "npm i" and "CDS Watch" than open app/product directory and ran "npm i" and "npm start" after tha application open but its showing nothing.

I check in developers mode of chrome
I see following error
![image](https://user-images.githubusercontent.com/22063881/147956423-b1b994a6-5cd5-492c-87ef-c5c88cc55852.png)

And in network tab i see following
![image](https://user-images.githubusercontent.com/22063881/147956503-e0bcf891-fee5-4b1e-a078-cb34c4e2a501.png)

Any guess what could be the problem?

**Comment by jcailan** [comment]
Hi @ahmedkhan29789 

I tried both VS Code and SAP BAS without any issues -- see below. In order to help alleviate any doubts on issues faced in SAP BAS, I would suggest to every now and then to try another IDE like VS Code.

![image](https://user-images.githubusercontent.com/27951983/148025790-5d0815da-f5cc-4d36-9ccb-e68eef468536.png)

**Comment by jcailan** [comment]
@ahmedkhan29789 - as a response to your second screenshot, make sure you got your CAP service working.
